name: "🐛 Bug"
description: "Reportar um comportamento inesperado."
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Descrição
      description: O que aconteceu?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: Liste os passos necessários para reproduzir o bug.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamento esperado
      description: O que deveria ter acontecido?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Contexto adicional
      description: Capturas de tela, logs, versão do Python, etc.
